src/OnlinePayment/newProject/routes/web.php
<?php

use App\Http\Controllers\AuditController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/logout', [LoginController::class, 'logout'])->name('logout');
Route::get('/Users', [UserController::class, 'getUsers'])->name('Users')->middleware('admin');
Route::resource('user', UserController::class);
Route::resource('role', RoleController::class)->middleware('admin');
Route::get('/search', [UserController::class, 'GetUser'])->name('search');
Route::get('/audit', [AuditController::class, 'showAudit'])->name('audit')->middleware('admin');
Route::get('profile/{id}/edit', [UserController::class, 'editProfile'])->name('editProfile');
Route::any('profile/{id}', [UserController::class, 'updateProfile'])->name('updateProfile');
Route::resource('company', CompanyController::class)->middleware('admin');
Route::resource('item', ItemController::class);
Route::resource('invoice', InvoiceController::class);

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

src/OnlinePayment/newProject/app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Company extends Model
{

    use HasFactory;
    protected $fillable=['company_name', 'email', 'location', 'phone'];

    public function user(){
        return $this->belongsTo(User::class, 'company_id', 'id');
    }
}

src/OnlinePayment/newProject/app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Http\Requests\CompanyRequest;
use App\Models\Company;
use App\Service\CompanyService;
use App\Service\FileService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;

/**
 * Class Company Controller
 */
class CompanyController extends Controller
{
    protected $companyService;
    protected $fileService;

    /**
     * @param CompanyService $companyService
     */
    public function __construct(CompanyService $companyService, FileService $fileService)
    {
        $this->fileService = $fileService;
        $this->companyService = $companyService;
    }


    /**
     *Display a listing of the companies.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\RedirectResponse
     */
    public function index(Request $request)
    {
        try {
            $total = intval(ceil(count(Company::all()) / 10));
            $companies = $this->companyService->getCompany($request->all());
            return view('Company.CompanyRetrieve', compact('companies', 'total'));
        } catch (\Exception $exception) {
            Log::error($exception);
            return redirect()->back()->with('error_msg', $exception);
        }
    }


    /**
     * Show the form for creating a new company.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\RedirectResponse
     */
    public function create()
    {
        try {
            return view('Company.CompanyForm');
        } catch (\Exception $exception) {
            Log::error($exception);
            return redirect()->back()->with('error_msg', $exception);
        }
    }


    /**
     * Store a newly created company in storage.
     *
     * @param CompanyRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CompanyRequest $request)
    {
        try {
            DB::beginTransaction();
            $company = $this->companyService->store([
                "company_name" => $request->company_name,
                "email" => $request->email,
                "location" => $request->location,
                "phone" => $request->phone
            ]);
            //$this->fileService->storeFile($company, $request, 'logo', 'company_image', 'company_image');
            DB::commit();
            return redirect()->route('company.index')->with('status', 'New Company Created');
        } catch (\Exception $exception) {

            Log::error($exception);
            return redirect()->back()->with('error_msg', $exception);
        }
    }


    /**
     * Display the specified company.
     *
     * @param Company $company
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\RedirectResponse
     */
    public function show(Company $company)
    {
        try {
            return view('Company.CompanyRetrieve', compact('company'));
        } catch (\Exception $exception) {
            Log::error($exception);
            return redirect()->back()->with('error_msg', $exception);
        }
    }

    /**
     * Show the form for editing the specified company.
     *
     * @param Company $company
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\RedirectResponse
     */
    public function edit(Company $company)
    {
        try {
            return view('Company.CompanyForm', compact('company'));
        } catch (\Exception $exception) {
            Log::error($exception);
            return redirect()->back()->with('error_msg', $exception);
        }
    }


    /**
     * Update the specified company in storage.
     *
     * @param CompanyRequest $request
     * @param Company $company
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(CompanyRequest $request, Company $company)
    {
        try {
            DB::beginTransaction();
            $company_update = $this->companyService->find($company->id);

            $this->companyService->update($company->id, [
                "company_name" => $request->company_name,
                "email" => $request->email,
                "location" => $request->location,
                "phone" => $request->phone
            ]);
            DB::commit();
            return redirect()->route('company.index')->with('status', 'Company Details Updated');
        } catch (\Exception $exception) {
            Log::error($exception);
            return redirect()->back()->with('error_msg', $exception);
        }
    }


    /**
     * Remove the specified company from storage.
     *
     * @param Company $company
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Company $company)
    {
        try {
            $this->companyService->destroy($company->id);
            return redirect()->route('company.index')->with('status', 'Company Details Deleted Successfully');
        } catch (\Exception $exception) {
            Log::error($exception);
            return redirect()->back()->with('error_msg', $exception);
        }
    }
}

src/OnlinePayment/newProject/resources/views/Company/CompanyForm.blade.php
@extends('layouts.app')
@canany(['create_user', 'update_user'])
@section('CssSection')
    <link rel="stylesheet" type="text/css" href="{{asset('css/company.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/bootstrap/css/bootstrap.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('fonts/font-awesome-4.7.0/css/font-awesome.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('fonts/Linearicons-Free-v1.0.0/icon-font.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/animate/animate.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/css-hamburgers/hamburgers.min.css"')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/animsition/css/animsition.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/select2/select2.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/daterangepicker/daterangepicker.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('css/util.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('css/main.css')}}">
@endsection

@section('title') Company @endsection
@section('body')

        @if (isset($company))
            <div class="limiter">
                <div class="container-login100">
                    <div class="wrap-login100">
                        <div class="login100-form-title" style="background-image: url({{asset('images/company.jpg')}});">
                            <span class="login100-form-title-1">
                                Edit Company
                            </span>
                        </div>
                        <form class="login100-form validate-form" action="{{route('company.update', $company->id)}}" method="post" enctype="multipart/form-data">
                             @csrf
                            @method('PUT')
                            <div class="wrap-input100 validate-input m-b-26" data-validate="Company Name is required">
                                <label class="label-input100" for="company_name">Name</label>
                                <input class="input100" type="text" name="company_name" id="company_name"
                                       value="{{$company->company_name}}" required placeholder="Enter name">
                                <span class="focus-input100"></span>
                            </div>

                            <div class="wrap-input100 validate-input m-b-18" data-validate = "Location is required">
                                <label class="label-input100" for="location">Location</label>
                                <input class="input100" type="text" name="location" id="location"
                                       value="{{$company->location}}" required placeholder="Enter location">
                                <span class="focus-input100"></span>
                            </div>

                            <div class="wrap-input100 validate-input m-b-18" data-validate = "Email is required">
                                <label class="label-input100" for="email">Email</label>
                                <input class="input100" type="email" name="email" id="email"
                                       value="{{$company->email}}" required placeholder="Enter email">
                                <span class="focus-input100"></span>
                            </div>

                            <div class="wrap-input100 validate-input m-b-18" data-validate = "Contact number is required">
                                <label class="label-input100" for="phone">Phone</label>
                                <input class="input100" type="number" name="phone" id="phone"
                                       value="{{$company->phone}}" required placeholder="Enter phone">
                                <span class="focus-input100"></span>
                            </div>

                            <div class="container-login100-form-btn">
                                <button class="login100-form-btn" type="submit" id="submit">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        @else
            <div class="limiter">

                <div class="container-login100">
                    <div class="wrap-login100">

                        <div class="login100-form-title" style="background-image: url({{asset('images/company.jpg')}});">
                            <span class="login100-form-title-1">
                                Create New Company
                            </span>
                        </div>

                        <form id="addPostForm" class="login100-form validate-form" action="{{route('company.store')}}" method="post" enctype="multipart/form-data">
                            @csrf
                            <div class="wrap-input100 validate-input m-b-26" data-validate="Company Name is required">
                                <label class="label-input100" for="company_name">Name</label>
                                <input class="input100" type="text" name="company_name" id="company_name"
                                       value="{{@old('company_name')}}" required placeholder="Enter name">
                                <span class="focus-input100"></span>
                            </div>

                            <div class="wrap-input100 validate-input m-b-18" data-validate = "Location is required">
                                <label class="label-input100" for="location">Location</label>
                                <input class="input100" type="text" name="location" id="location"
                                       value="{{@old('location')}}" required placeholder="Enter location">
                                <span class="focus-input100"></span>
                            </div>

                            <div class="wrap-input100 validate-input m-b-18" data-validate = "Email is required">
                                <label class="label-input100" for="email">Email</label>
                                <input class="input100" type="email" name="email" id="email"
                                       value="{{@old('email')}}" required placeholder="Enter email">
                                <span class="focus-input100"></span>
                            </div>

                            <div class="wrap-input100 validate-input m-b-18" data-validate = "Contact number is required">
                                <label class="label-input100" for="phone">Phone</label>
                                <input class="input100" type="number" name="phone" id="phone"
                                       value="{{@old('phone')}}" required placeholder="Enter phone number">
                                <span class="focus-input100"></span>
                            </div>

                            <div class="container-login100-form-btn">
                                <button class="login100-form-btn" type="submit" id="submit">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

    @endif
@endsection

@section('JsSection')
    <script src="{{asset('vendor/jquery/jquery-3.2.1.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/animsition/js/animsition.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/bootstrap/js/popper.js')}}"></script>
    <script src="{{asset('vendor/bootstrap/js/bootstrap.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/select2/select2.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/daterangepicker/moment.min.js')}}"></script>
    <script src="{{asset('vendor/daterangepicker/daterangepicker.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/countdowntime/countdowntime.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('js/main.js')}}"></script>

@endsection

@endcanany

src/OnlinePayment/newProject/resources/views/Company/CompanyRetrieve.blade.php
@extends('layouts.app')
@can('access_company')
@section('CssSection')

    <link rel="stylesheet" type="text/css" href="{{asset('css/company.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/bootstrap/css/bootstrap.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('fonts/font-awesome-4.7.0/css/font-awesome.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('fonts/Linearicons-Free-v1.0.0/icon-font.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/animate/animate.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/css-hamburgers/hamburgers.min.css"')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/animsition/css/animsition.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/select2/select2.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/daterangepicker/daterangepicker.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('css/util.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('css/main.css')}}">
@endsection
@section('title') Company @endsection
@section('body')
    <div class="container">
    @if (session('status'))
        <div class="alert alert-success">{{session('status')}}</div>
    @endif
    @if (session('error_msg'))
        <div class="alert alert-success">{{session('msg')}}</div>
    @endif
    @if(isset($companies))


            <button class="btn btn-primary text-white"><a class="text-white" style="text-decoration: none" href="{{route('company.create')}}">Add New Company</a></button>
            <br/>
            <hr/>
        <form class="d-flex" action="{{route('company.index')}}" method="GET">
            <input class="form-control me-2" type="search" name="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        <table class="table table-hover">
            <thead>
            <tr>
                @if (!request()->has('sort') and !request()->has('order'))
                    <th scope="col" class="column_sort" id="sn">
                        <a href="{{request()->fullUrlWithQuery(['sort'=>'desc', 'order'=>'id'])}}">SN</a></th>
                    <th scope="col" class="column_sort" id="company_name"><a
                            href="{{request()->fullUrlWithQuery(['sort'=>'desc', 'order'=>'name'])}}">
                            Name</a></th>
                    <th scope="col" class="column_sort" id="email">
                        <a href="{{request()->fullUrlWithQuery(['sort'=>'desc', 'order'=>'email'])}}">Email</a></th>
                @elseif (request()->has('sort') and request()->has('order'))
                    @php
                        if (request()->get('sort')=='desc'){
            $sort='asc';
        }
        else{
            $sort='desc';
        }
                    @endphp
                    <th scope="col" class="column_sort" id="sn">
                        <a href="{{request()->fullUrlWithQuery(['sort'=>$sort, 'order'=>'id'])}}">SN</a></th>
                    <th scope="col" class="column_sort" id="company_name"><a
                            href="{{request()->fullUrlWithQuery(['sort'=>$sort, 'order'=>'name'])}}">
                            Name</a></th>
                    <th scope="col" class="column_sort" id="email">
                        <a href="{{request()->fullUrlWithQuery(['sort'=>$sort, 'order'=>'email'])}}">Email</a></th>

                @endif
                <th scope="col">View</th>
                <th scope="col">Edit</th>
                <th scope="col">Delete</th>
            </tr>
            </thead>
            <tbody id="CompanyTable">


            <?php $index = 1?>
            @foreach($companies as $company)

                <tr>
                    <td>{{$index}}</td>
                    <td>{{$company->company_name}}</td>
                    <td>{{$company->email}}</td>
                    <td><a class="fa fa-eye" href="{{route('company.show', $company->id)}}"></a></td>
                    <td><a class="fa fa-edit" href="{{route('company.edit', $company->id)}}"></a></td>
                    <td>
                        <form action="{{route('company.destroy', $company->id)}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="fa fa-trash"></button>
                        </form>
                    </td>
                </tr>

                <?php $index++;?>
            @endforeach<br>
            </tbody>
        </table>
        <br/>
        <hr/>
        <nav aria-label="...">
            <ul class="pagination justify-content-center">
                @for ($i=1; $i<=$total; $i++)
                    <li class="page-item"><a class="page-link" id="{{$i}}" onclick="make_active({{$i}})"
                                             href="{{request()->fullUrlWithQuery(['page'=>$i])}}">{{$i}}</a></li>
                @endfor

            </ul>
        </nav>
        </div>

    @else

        <div class="limiter">
            <div class="container-login100">
                <div class="wrap-login100">
                    <div class="login100-form-title" style="background-image: url({{asset('images/company.jpg')}});">
                            <span class="login100-form-title-1">
                                Company Info
                            </span>
                    </div>
                    <form class="login100-form validate-form" enctype="multipart/form-data">

                    <div class="wrap-input100 validate-input m-b-18">
                            <label class="label-input100" for="name">Name</label>
                            <input readonly class="input100" type="text" name="name" id="name"
                                   value="{{$company->company_name}}">
                        </div>

                        <div class="wrap-input100 validate-input m-b-18">
                            <label  class="label-input100" for="email">Email</label>
                            <input readonly class="input100" type="email" name="email" id="email"
                                   value="{{$company->email}}" >
                        </div>

                        <div class="wrap-input100 validate-input m-b-18">
                            <label class="label-input100" for="location">Location</label>
                            <input readonly class="input100" type="text" name="location" id="location"
                                   value="{{$company->location}}">

                        </div>

                        <div class="wrap-input100 validate-input m-b-18" >
                            <label class="label-input100" for="phone">Phone</label>
                            <input readonly class="input100" type="password" name="phone" id="phone"
                            value="{{$company->phone}}">
                        </div>
                    </form>
                </div>
            </div>
        </div>

    @endif

@endsection

@section('JsSection')
    <script src="{{ asset('js/UserRetrieve.js') }}"></script>

    <script src="{{asset('vendor/jquery/jquery-3.2.1.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/animsition/js/animsition.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/bootstrap/js/popper.js')}}"></script>
    <script src="{{asset('vendor/bootstrap/js/bootstrap.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/select2/select2.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/daterangepicker/moment.min.js')}}"></script>
    <script src="{{asset('vendor/daterangepicker/daterangepicker.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/countdowntime/countdowntime.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('js/main.js')}}"></script>

@endsection

@endcan