src/OnlinePayment/newProject/routes/web.php
<?php

use App\Http\Controllers\AuditController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/logout', [LoginController::class, 'logout'])->name('logout');
Route::get('/Users', [UserController::class, 'getUsers'])->name('Users')->middleware('admin');
Route::resource('user', UserController::class);
Route::resource('role', RoleController::class)->middleware('admin');
Route::get('/search', [UserController::class, 'GetUser'])->name('search');
Route::get('/audit', [AuditController::class, 'showAudit'])->name('audit')->middleware('admin');
Route::get('profile/{id}/edit', [UserController::class, 'editProfile'])->name('editProfile');
Route::any('profile/{id}', [UserController::class, 'updateProfile'])->name('updateProfile');
Route::resource('company', CompanyController::class)->middleware('admin');
Route::resource('item', ItemController::class);
Route::resource('invoice', InvoiceController::class);

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

src/OnlinePayment/newProject/app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Http\Requests\RoleRequest;
use App\Service\RoleService;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

/**
 * Class Role Controller
 */
class RoleController extends Controller
{
    protected $roleService;

    /**
     * @param RoleService $roleService
     */
    public function __construct(RoleService $roleService)
    {
        $this->roleService = $roleService;
    }


    /**
     * Displaying list of roles
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\RedirectResponse
     */
    public function index()
    {
        try {
            $roles = $this->roleService->index();
            return view('Roles.RoleView')->with('result', $roles)->with('status', 'Search Results');
        } catch (\Exception $exception) {
            Log::error($exception);
            return redirect()->back()->with('error_msg', $exception);
        }
    }

    /**
     * Show the form for creating a new role.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\RedirectResponse
     */
    public function create()
    {
        try {
            $permissions = $this->roleService->create();
            return view('Roles.RoleForm', compact('permissions'));
        } catch (\Exception $exception) {
            Log::error($exception);
            return redirect()->back()->with('error_msg', $exception);
        }
    }


    /**
     * Store a newly created role in storage.
     *
     * @param RoleRequest $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\RedirectResponse|void
     */
    public function store(RoleRequest $request)
    {
        try {
            if (Auth::user()->can('manage_role')) {
                DB::beginTransaction();
                $role = $this->roleService->store([
                    'name' => $request->name
                ]);
                $permissions = $request->permissions;
                foreach ($permissions as $permission) {
                    $role->givePermissionTo($permission);
                }
                DB::commit();
                return redirect()->route('role.index')->with('status', 'Role Created Successfully');
            } else {
                return view('Role.RoleForm');
            }
        } catch (\Exception $exception) {
            Log::error($exception);
            return redirect()->back()->with('error_msg', $exception);
        }
    }


    /**
     *  Show the form for editing the specified role.
     *
     * @param $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\RedirectResponse
     */
    public function edit($id)
    {
        try {
            if (Auth::user()->can('manage_role')) {
                $role = Role::findorfail($id);
                $permissions = Permission::all();
                $roles_permissions = DB::table('role_has_permissions')->where('role_id', $id)->get();
                $selectedperm = [];
                foreach ($roles_permissions as $rolepermission) {
                    $selectedperm[] = $rolepermission->permission_id;
                }
                return view('Roles.RoleForm', compact('role', 'permissions', 'selectedperm'));
            } else {
                return view('Roles.RoleForm');
            }
        } catch (\Exception $exception) {
            Log::error($exception);
            return redirect()->back()->with('error_msg', $exception);
        }

    }

    /**
     * Update the specified role in storage.
     *
     * @param RoleRequest $request
     * @param $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\RedirectResponse|void
     */
    public function update(RoleRequest $request, $id)
    {
        try {
            if (Auth::user()->can('manage_role')) {
                DB::beginTransaction();
                $role = Role::findorfail($id);
                $this->roleService->update([
                    "name" => $request->name
                ], $id);
                $permissions = $request->permissions;
                $perm = [];
                foreach ($permissions as $permission) {
                    $perm[] = $permission;
                    $role->permissions()->sync($perm);
                }
                $role->save();
                DB::commit();
                return redirect()->route('role.index')->with('status', 'Role Updated Successfully');
            } else {
                return view('Roles.RoleForm');
            }
        } catch (\Exception $exception) {
            Log::error($exception);
            return redirect()->back()->with('error_msg', $exception);
        }

    }

    /**
     * Remove the specified role from storage.
     *
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|void
     */
    public function destroy($id)
    {
        try {
            DB::beginTransaction();
            $this->roleService->destroy($id);
            DB::commit();
            return redirect()->route('role.index');
        } catch (\Exception $exception) {
            Log::error($exception);
            return redirect()->back()->with('error_msg', $exception);
        }
    }
}

src/OnlinePayment/newProject/resources/views/Roles/RoleForm.blade.php
@extends('layouts.app')
@section('CssSection')

    <link rel="stylesheet" type="text/css" href="{{asset('css/company.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/bootstrap/css/bootstrap.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('fonts/font-awesome-4.7.0/css/font-awesome.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('fonts/Linearicons-Free-v1.0.0/icon-font.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/animate/animate.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/css-hamburgers/hamburgers.min.css"')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/animsition/css/animsition.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/select2/select2.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/daterangepicker/daterangepicker.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('css/util.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('css/main.css')}}">
@endsection
@can('manage_role')
@section('title') User @endsection
@section('body')
    <div class="container">
    @if (session('error_msg'))
        <div class="alert alert-success">{{session('msg')}}</div>
    @endif
    @if(isset($selectedperm))
        <div class="right_col" role="main">
            <h1 class="mt-3">Edit Role  <a href="{{route('role.index')}}" class="btn btn-primary btn-sm"> <i aria-hidden="true"></i> View Roles</a></h1>
            <div class="card mt-3">
                <div class="row">
                    <div class="col-md-6">
                        <form action="{{route('role.update', $role->id)}}" method="POST" class="bg-light p-3">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="name">Role Name: </label>
                                <input type="text" name="name" class="form-control" value="{{$role->name}}" placeholder="Enter Role Name">
                                @error('name')
                                <p class="text-danger">{{$message}}</p>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="permission">Permissions </label><br>
                                @foreach ($permissions as $permission)
                                    <input type="checkbox" name="permissions[]" value="{{$permission->id}}"
                                    @if(in_array($permission->id, $selectedperm))
                                        {{"checked"}}
                                        @else
                                        {{""}}
                                        @endif> {{$permission->name}} <br>
                                @endforeach
                            </div>
                            <button type="submit" class="btn btn-success">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    @else
        <div class="right_col" role="main">
            <h1 class="mt-3">Create Role  <a href="{{route('role.index')}}" class="btn btn-primary btn-sm"> <i aria-hidden="true"></i> View Roles</a></h1>
            <div class="card mt-3">
                <div class="row">
                    <div class="col-md-6">
                        <form action="{{route('role.store')}}" method="POST" class="bg-light p-3">
                            @csrf
                            @method('POST')
                            <div class="form-group">
                                <label for="name">Role Name: </label>
                                <input type="text" name="name" class="form-control" value="{{@old('name')}}" placeholder="Enter Role Name">
                                @error('name')
                                <p class="text-danger">{{$message}}</p>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="permission">Permissions </label><br>

                                @foreach ($permissions as $permission)
                                    <input type="checkbox" name="permissions[]" value="{{$permission->id}}"> {{$permission->name}} <br>
                                @endforeach
                            </div>


                            <button type="submit" class="btn btn-success">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    @endif
    </div>
@endsection
@endcan


@section('JsSection')
    <script src="{{asset('vendor/jquery/jquery-3.2.1.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/animsition/js/animsition.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/bootstrap/js/popper.js')}}"></script>
    <script src="{{asset('vendor/bootstrap/js/bootstrap.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/select2/select2.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/daterangepicker/moment.min.js')}}"></script>
    <script src="{{asset('vendor/daterangepicker/daterangepicker.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/countdowntime/countdowntime.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('js/main.js')}}"></script>

@endsection

src/OnlinePayment/newProject/resources/views/Roles/RoleView.blade.php
@extends('layouts.app')
@section('CssSection')

    <link rel="stylesheet" type="text/css" href="{{asset('css/company.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/bootstrap/css/bootstrap.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('fonts/font-awesome-4.7.0/css/font-awesome.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('fonts/Linearicons-Free-v1.0.0/icon-font.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/animate/animate.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/css-hamburgers/hamburgers.min.css"')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/animsition/css/animsition.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/select2/select2.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/daterangepicker/daterangepicker.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('css/util.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('css/main.css')}}">
@endsection
@can('manage_role')

@section('title') User @endsection
@section('body')
    <div class="container">
    @if (session('status'))
        <div class="alert alert-success">{{session('status')}}</div>
    @endif
    @if (session('error_msg'))
        <div class="alert alert-success">{{session('msg')}}</div>
    @endif
        <button class="btn btn-primary text-white"><a class="text-white" style="text-decoration: none" href="{{route('role.create')}}">Add New Role</a></button>
<br/>
        <hr/>

    <table class="table table-hover">
        <thead>
        <tr>
            <th class="text-center">SN</th>
            <th class="text-center">Roles</th>
            <th class="text-center">Permissions</th>
            <th class="text-center">Edit</th>
            <th class="text-center">Delete</th>

        </tr>
        </thead>
        <tbody>
        <?php $index = 1;?>
        @foreach($result as $role)
            <tr>
                <td class="text-center">{{$index}}</td>
                <td class="text-center">{{$role->name}}</td>
                <td class="text-center">@foreach($role->permissions as $rp)
                        @if ($rp['pivot']['role_id']===$role->id)
                            {{$rp['name']}}
                            <br>
                        @endif
                    @endforeach</td>
                <td class="text-center">
                    <a class="fa fa-edit" href="{{route('role.edit', $role->id)}}"></a>
                </td>
                <td class="text-center">
                    <form action="{{url('role/'.$role->id)}}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="fa fa-trash"></button>
                    </form>
                </td>
            </tr>

            <?php $index++;?>
        @endforeach
        </tbody>
    </table>
        <hr/>
    </div>
@endsection
@endcan


@section('JsSection')
    <script src="{{asset('vendor/jquery/jquery-3.2.1.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/animsition/js/animsition.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/bootstrap/js/popper.js')}}"></script>
    <script src="{{asset('vendor/bootstrap/js/bootstrap.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/select2/select2.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/daterangepicker/moment.min.js')}}"></script>
    <script src="{{asset('vendor/daterangepicker/daterangepicker.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/countdowntime/countdowntime.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('js/main.js')}}"></script>

@endsection