src/OnlinePayment/newProject/routes/web.php
<?php

use App\Http\Controllers\AuditController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/logout', [LoginController::class, 'logout'])->name('logout');
Route::get('/Users', [UserController::class, 'getUsers'])->name('Users')->middleware('admin');
Route::resource('user', UserController::class);
Route::resource('role', RoleController::class)->middleware('admin');
Route::get('/search', [UserController::class, 'GetUser'])->name('search');
Route::get('/audit', [AuditController::class, 'showAudit'])->name('audit')->middleware('admin');
Route::get('profile/{id}/edit', [UserController::class, 'editProfile'])->name('editProfile');
Route::any('profile/{id}', [UserController::class, 'updateProfile'])->name('updateProfile');
Route::resource('company', CompanyController::class)->middleware('admin');
Route::resource('item', ItemController::class);
Route::resource('invoice', InvoiceController::class);

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

src/OnlinePayment/newProject/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;
use OwenIt\Auditing\Contracts\Auditable;

class User extends Authenticatable implements Auditable
{
    use HasFactory, Notifiable, HasRoles, \OwenIt\Auditing\Auditable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password','phone_number', 'filename', 'gender_id', 'status_id', 'company_id'
    ];


    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function gender(){
        return $this->belongsTo(Gender::class, 'gender_id', 'id');
    }

    public function status(){
        return $this->belongsTo(Status::class, 'status_id', 'id');
    }

    public function company(){
        return $this->hasOne(Company::class, 'company_id', 'id');
    }

    public function role()
    {
        return $this->hasOne(RolePermission::class, 'role_id', 'role_id');
    }
}

src/OnlinePayment/newProject/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Http\Requests\UserRequest;
use App\Http\Requests\ProfileRequest;
use App\Models\Company;
use App\Models\Profile;
use App\Models\User;
use app\Repository\UserRepo;
use App\Service\FileService;
use App\Service\UserService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Storage;
use PHPUnit\Framework\Exception;
use Spatie\Permission\Models\Role;


class UserController extends Controller
{
    protected $userService;
    protected $userRepository;
    protected $fileService;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(UserService $userService, UserRepo $userRepository)
    {
        $this->userRepository = $userRepository;
        $this->userService = $userService;
    }

    /**
     * Display a listing of the users.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\RedirectResponse
     */
    public function getUsers(Request $req)
    {
        try {
            $total = intval(ceil(count(User::all()) / 10));
            $result = $this->userService->getUsers($req->all());
            return view('User.UserRetrieve')->with('result', $result)->with('total', $total)->with('status', 'Search Results');
        } catch (\Exception $exception) {
            Log::error($exception);
            return redirect()->back()->with('error_msg', $exception);
        }
    }


    /**
     * Show the form for creating a new user.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\RedirectResponse
     */
    public function create()
    {
        try {
            $roles = Role::all();
            $companies = Company::all();
            return view('User.UserForm', compact('roles', 'companies'));
        } catch (\Exception $exception) {
            Log::error($exception);
            return redirect()->back()->with('error_msg', $exception);
        }
    }

    /**
     * Store a newly created role in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(UserRequest $req)
    {
        //$users = User::where('id', '!=', \auth()->user()->id)->get();
        try {
            DB::beginTransaction();
            $user = $this->userService->store([
                "name" => $req->name,
                "email" => $req->email,
                "password" => bcrypt($req->password),
                "company_id" => $req->company
            ]);
            $roles = $req->roles;

            foreach ($roles as $role) {
                $user->assignRole($role);
            }
            DB::commit();
            return redirect()->route('Users')->with('status', 'New User Created');
        } catch (Exception $exception) {
            Log::error($exception);
            return redirect()->back()->with('error_msg', $exception);
        }
    }


    /**
     * Show the form for editing the specified user.
     *
     * @param int $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\RedirectResponse
     */
    public function edit($id)
    {

        try {
            DB::beginTransaction();
            $user_id = $this->userService->edit($id);
            $model_roles = DB::table('model_has_roles')->where('model_id', $id)->get();
            $selected_roles = [];
            $roles = Role::all();
            foreach ($model_roles as $role) {
                $selected_roles[] = $role->role_id;
            }
            return view('User.UserForm', compact('user_id', 'selected_roles', 'roles'));
            DB::commit();
        } catch (\Exception $exception) {
            Log::error($exception);
            return redirect()->back()->with('error_msg', $exception);
        }

    }

    /**
     * Update the specified user in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UserRequest $req, $id)
    {

        try {
            DB::beginTransaction();
            $this->userService->update($id, $req->all());
            DB::commit();
            return redirect()->route('Users')->with('status', 'User Details Updated');
        } catch (\Exception $exception) {
            Log::error($exception);
            return redirect()->back()->with('error_msg', $exception);
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        try {
            DB::beginTransaction();
            $this->userService->destroy($id);
            DB::commit();
            return redirect()->route('Users');
        } catch (\Exception $exception) {
            Log::error($exception);
            return redirect()->back()->with('error_msg', $exception);
        }
    }

    public function editProfile($id)
    {
        try {
            $all = $this->userService->editProfile($id);
            $gender = $all[0];
            $status = $all[1];
            $profile = $all[2];
            return view('Profile.ProfileForm', compact('profile', 'gender', 'status'));
        } catch (\Exception $exception) {
            Log::error($exception);
            return redirect()->back()->with('error_msg', $exception);
        }
    }

    public function updateProfile(ProfileRequest $request, $id)
    {
        try {
            $gender = $this->userRepository->all();
            $status = $this->userRepository->getStatus();
            $profile = $this->userRepository->findWithRelation($id);
            $profile->phone_number = $request->number;
            $profile->gender_id = $request->gender;
            $profile->status_id = $request->status;
            $profile->save();
            return redirect()->route('editProfile', $id)->with('gender', $gender)->with('status', $status)->with('profile', $profile)->with('status', 'Updated Successfully');
        } catch (\Exception $exception) {
            Log::error($exception);
            return redirect()->back()->with('error_msg', $exception);
        }
    }
}

src/OnlinePayment/newProject/resources/views/User/UserForm.blade.php
@extends('layouts.app')
@section('CssSection')

    <link rel="stylesheet" type="text/css" href="{{asset('css/company.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/bootstrap/css/bootstrap.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('fonts/font-awesome-4.7.0/css/font-awesome.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('fonts/Linearicons-Free-v1.0.0/icon-font.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/animate/animate.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/css-hamburgers/hamburgers.min.css"')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/animsition/css/animsition.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/select2/select2.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/daterangepicker/daterangepicker.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('css/util.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('css/main.css')}}">
@endsection
@canany(['create_user', 'update_user'])


@section('title') User @endsection
@section('body')
    @if (session('error_msg'))
        <div class="alert alert-success">{{session('msg')}}</div>
    @endif

        @if (isset($user_id))
            <div class="limiter">
                <div class="container-login100">
                    <div class="wrap-login100">
                        <div class="login100-form-title" style="background-image: url({{asset('images/bg-01.jpg')}});">
                            <span class="login100-form-title-1">
                                Edit User
                            </span>
                        </div>
                        <form class="login100-form validate-form" action="{{url('user/'.$user_id->id)}}" method="post" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')

                            <div class="wrap-input100 validate-input m-b-18" data-validate = "Name is required">
                                <label class="label-input100" for="name">Name</label>
                                <input class="input100" type="text" name="name" id="name"
                                       value="{{$user_id->name}}" required placeholder="Enter name">
                                <span class="focus-input100"></span>
                            </div>

                            <div class="wrap-input100 validate-input m-b-18" data-validate = "Email is required">
                                <label class="label-input100" for="email">Email</label>
                                <input class="input100" type="email" name="email" id="email"
                                       value="{{$user_id->email}}" required placeholder="Enter email">
                                <span class="focus-input100"></span>
                            </div>

                            <div class="wrap-input100 validate-input m-b-18" data-validate = "Password is required">
                                <label class="label-input100" for="password">Password</label>
                                <input class="input100" type="password" name="password" id="password"
                                       value="{{$user_id->password}}" required placeholder="Enter password">
                                <span class="focus-input100"></span>
                            </div>

                            <div class="form-check form-check-inline validate-input m-b-18" data-validate = "Role is required">
                                <label class="label-input100 form-check-label" for="roles[]">Roles</label>
                                @foreach ($roles as $role)
                                    <input class="form-check-input" type="checkbox" name="roles[]" value="{{$role->id}}"
                                    @if(in_array($role->id, $selected_roles))
                                        {{"checked"}}
                                        @else
                                        {{""}}
                                        @endif> {{$role->name}} <br>
                                @endforeach
                                <span class="focus-input100"></span>
                            </div>


                            <div class="container-login100-form-btn">
                                <button class="login100-form-btn" type="submit" id="submit">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        @else
            <div class="limiter">
                <div class="container-login100">
                    <div class="wrap-login100">
                        <div class="login100-form-title" style="background-image: url({{asset('images/bg-01.jpg')}});">
                            <span class="login100-form-title-1">
                                Create New User
                            </span>
                        </div>
                        <form class="login100-form validate-form" action="{{route('user.store')}}" method="post" enctype="multipart/form-data">
                            @csrf
                            <div class="wrap-input100 validate-input m-b-18" data-validate = "Name is required">
                                <label class="label-input100" for="name">Name</label>
                                <input class="input100" type="text" name="name" id="name"
                                       value="{{@old('name')}}" required placeholder="Enter name">
                                <span class="focus-input100"></span>
                            </div>

                            <div class="wrap-input100 validate-input m-b-18" data-validate = "Email is required">
                                <label class="label-input100" for="email">Email</label>
                                <input class="input100" type="email" name="email" id="email"
                                       value="{{@old('email')}}" required placeholder="Enter email">
                                <span class="focus-input100"></span>
                            </div>

                            <div class="wrap-input100 validate-input m-b-18" data-validate = "Password is required">
                                <label class="label-input100" for="password">Password</label>
                                <input class="input100" type="password" name="password" id="password"
                                       value="{{@old('password')}}" required placeholder="Enter password">
                                <span class="focus-input100"></span>
                            </div>

                            <div class="wrap-input100 validate-input m-b-18" data-validate = "Confirm Password is required">
                                <label class="label-input100" for="password-confirm">Confirm Password</label>
                                <input class="input100" type="password" name="password_confirmation" id="password-confirm"
                                       required placeholder="Enter password" autocomplete="new-password">
                                <span class="focus-input100"></span>
                            </div>

                            <div class="input100 validate-input m-b-18" data-validate = "Company is required">
                                <label class="label-input100" for="company">Company</label>
                                <select class="input100" name="company" id="company">
                                    @foreach($companies as $company)
                                        <option value="{{$company->id}}">{{$company->company_name}}</option>
                                    @endforeach
                                </select><br>
                                <span class="focus-input100"></span>
                            </div>

                            <div class=" form-check form-check-inline validate-input m-b-18" data-validate = "Role is required">
                                <label class="label-input100 form-check-label" for="role">Role</label>
                                @foreach ($roles as $role)
                                    <input class=" form-check-input" type="checkbox" name="roles[]" value="{{$role->name}}"> {{$role->name}} <br>
                                @endforeach
                                <span class="focus-input100"></span>
                            </div>

                            <div class="container-login100-form-btn">
                                <button class="login100-form-btn" type="submit" id="submit">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        @endif

@endsection

@section('JsSection')
    <script src="{{asset('vendor/jquery/jquery-3.2.1.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/animsition/js/animsition.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/bootstrap/js/popper.js')}}"></script>
    <script src="{{asset('vendor/bootstrap/js/bootstrap.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/select2/select2.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/daterangepicker/moment.min.js')}}"></script>
    <script src="{{asset('vendor/daterangepicker/daterangepicker.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/countdowntime/countdowntime.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('js/main.js')}}"></script>

@endsection

@endcanany

src/OnlinePayment/newProject/resources/views/User/UserRetrieve.blade.php
@extends('layouts.app')
@section('CssSection')

    <link rel="stylesheet" type="text/css" href="{{asset('css/company.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/bootstrap/css/bootstrap.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('fonts/font-awesome-4.7.0/css/font-awesome.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('fonts/Linearicons-Free-v1.0.0/icon-font.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/animate/animate.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/css-hamburgers/hamburgers.min.css"')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/animsition/css/animsition.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/select2/select2.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/daterangepicker/daterangepicker.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('css/util.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('css/main.css')}}">
@endsection
@if (session('status'))
    <div class="alert alert-success">{{session('status')}}</div>
@endif
@can('access_user')

@section('title') User @endsection
@section('body')
    <div class="container">
    @if (session('status'))
        <div class="alert alert-success">{{session('status')}}</div>
    @endif
    @if (session('error_msg'))
        <div class="alert alert-success">{{session('msg')}}</div>
    @endif
        <button class="btn btn-primary text-white">

        <a class="text-white" style="text-decoration: none" href="{{route('user.create')}}">Add New User</a>
        </button>
<br/>
        <hr/>
    <form class="d-flex" action="{{route('Users')}}" method="GET">
        <input class="form-control me-2" type="search" name="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
    <input type="hidden" id="order" name="order">
    <input type="hidden" id="id" name="id">
    <table class="table table-hover">
        <thead>
        <tr>
            @if (!request()->has('sort') and !request()->has('order'))
                <th scope="col" class="column_sort" id="sn">
                    <a href="{{request()->fullUrlWithQuery(['sort'=>'desc', 'order'=>'id'])}}">SN</a></th>
                <th scope="col" class="column_sort" id="name"><a
                        href="{{request()->fullUrlWithQuery(['sort'=>'desc', 'order'=>'name'])}}">
                        Name</a></th>
                <th scope="col" class="column_sort" id="email">
                    <a href="{{request()->fullUrlWithQuery(['sort'=>'desc', 'order'=>'email'])}}">Email</a></th>
            @elseif (request()->has('sort') and request()->has('order'))
                @php
                    if (request()->get('sort')=='desc'){
        $sort='asc';
    }
    else{
        $sort='desc';
    }
                @endphp
                <th scope="col" class="column_sort" id="sn">
                    <a href="{{request()->fullUrlWithQuery(['sort'=>$sort, 'order'=>'id'])}}">SN</a></th>
                <th scope="col" class="column_sort" id="name"><a
                        href="{{request()->fullUrlWithQuery(['sort'=>$sort, 'order'=>'name'])}}">
                        Name</a></th>
                <th scope="col" class="column_sort" id="email">
                    <a href="{{request()->fullUrlWithQuery(['sort'=>$sort, 'order'=>'email'])}}">Email</a></th>

            @endif
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody id="CompanyTable">

        @if (isset($result))
            <?php $index = 1?>
            {{--        @dd($search->name);--}}
            @foreach($result as $user)

                <tr>
                    <td>{{$index}}</td>
                    <td>{{$user->name}}</td>
                    <td>{{$user->email}}</td>
                    <td><a class="fa fa-edit" href="{{route('user.edit', $user->id)}}"></a></td>
                    <td>
                        <form action="{{url('user/'.$user->id)}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="fa fa-trash"></button>
                        </form>
                    </td>
                </tr>

                <?php $index++;?>
            @endforeach<br>
        </tbody>
    </table>
        <hr/>

        <nav aria-label="..." >
            <ul class="pagination justify-content-center">
                @for ($i=1; $i<=$total; $i++)
                    <li class="page-item"><a class="page-link" id="{{$i}}" onclick="make_active({{$i}})" href="{{request()->fullUrlWithQuery(['page'=>$i])}}">{{$i}}</a></li>
                @endfor

            </ul>
        </nav>

    @else
        <?php $index = 1;?>
        {{ $users -> links()}}
        @foreach($users as $user)

            <tr>
                <td>{{$index}}</td>
                <td>{{$user->name}}</td>
                <td>{{$user->email}}</td>
                <td><a class="fa fa-edit" href="{{route('user.edit', $user->id)}}"></a></td>
                <td>
                    <form action="{{url('user/'.$user->id)}}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="fa fa-trash"></button>
                    </form>
                </td>
            </tr>
            <?php $index++;?>
        @endforeach<br>
        </tbody>
    @endif
    </div>

@endsection
@endcan


@section('JsSection')
    <script src="{{ asset('js/UserRetrieve.js') }}"></script>

    <script src="{{asset('vendor/jquery/jquery-3.2.1.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/animsition/js/animsition.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/bootstrap/js/popper.js')}}"></script>
    <script src="{{asset('vendor/bootstrap/js/bootstrap.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/select2/select2.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/daterangepicker/moment.min.js')}}"></script>
    <script src="{{asset('vendor/daterangepicker/daterangepicker.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/countdowntime/countdowntime.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('js/main.js')}}"></script>

@endsection