src/OnlinePayment/newProject/routes/web.php
<?php

use App\Http\Controllers\AuditController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/logout', [LoginController::class, 'logout'])->name('logout');
Route::get('/Users', [UserController::class, 'getUsers'])->name('Users')->middleware('admin');
Route::resource('user', UserController::class);
Route::resource('role', RoleController::class)->middleware('admin');
Route::get('/search', [UserController::class, 'GetUser'])->name('search');
Route::get('/audit', [AuditController::class, 'showAudit'])->name('audit')->middleware('admin');
Route::get('profile/{id}/edit', [UserController::class, 'editProfile'])->name('editProfile');
Route::any('profile/{id}', [UserController::class, 'updateProfile'])->name('updateProfile');
Route::resource('company', CompanyController::class)->middleware('admin');
Route::resource('item', ItemController::class);
Route::resource('invoice', InvoiceController::class);

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

src/OnlinePayment/newProject/app/Models/InvoiceItem.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class InvoiceItem extends Model
{
    use HasFactory;

    protected $fillable = ['item_id', 'invoice_id', 'quantity'];

    public function item(){
        return $this->belongsTo(Items::class, 'item_id', 'id');
    }

    public function invoice(){
        return $this->belongsTo(Invoice::class, 'invoice_id', 'id');
    }
}

src/OnlinePayment/newProject/resources/views/InvoiceItem/InvoiceItemForm.blade.php
@extends('layouts.app')
@section('CssSection')

    <link rel="stylesheet" type="text/css" href="{{asset('css/company.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/bootstrap/css/bootstrap.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('fonts/font-awesome-4.7.0/css/font-awesome.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('fonts/Linearicons-Free-v1.0.0/icon-font.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/animate/animate.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/css-hamburgers/hamburgers.min.css"')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/animsition/css/animsition.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/select2/select2.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/daterangepicker/daterangepicker.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('css/util.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('css/main.css')}}">
@endsection
@section('body')
    <div class="contain">
        @if (session('status'))
            <div class="alert alert-success">{{session('status')}}</div>
        @endif
        @if(isset($invoice))
                <div class="container">
                    <div class="bg-white m-3 p-3">
            <form method="post" action="{{route('invoice.update', $invoice->id)}}">
                @csrf
                @method('PUT')
                <div id="invoice">
                    <form id="AddForm" name="addForm" method="post">
                        @csrf
                        <div id="item-container">
                            @foreach ($arr as $k=>$v)
                                @foreach ($v as $key=>$value)
                                    <div class="row">
                                        <div class="col-3">
                                            <input required type="text" id="iName" class="iName" name="iName[]" onkeyup="abcd(Increment)"  placeholder="Item Name" value="{{$value['name']}}">
                                        </div>
                                        <div class="col-3">
                                            <input required type="number" id="cost" class="cost" name="cost[]" placeholder="Price" value="{{$value['cost']}}">
                                        </div>
                                        <div class="col-3">
                                            <input required type="number" id="quantity" name="qty[]" onkeyup="itemValue(Increment)" placeholder="Quantity" value="{{$value['quantity']}}">
                                        </div>
                                        <div class="col-3">
                                            <button type="button" id="bt" class="btn btn-danger" onclick="return this.parentNode.parentNode.remove(); ">Delete</button>
                                        </div>
                                    </div>

                                @endforeach
                            @endforeach
                        </div>
                        <ul id="myUL"></ul>
                        <a class="text-white btn btn-primary" style="text-decoration: none" id="add-new-item">Add New Item</a>
                        <br/>
                        <hr/>
                    </form><br>

                    <span id="SpanForm" class="error">@error('addForm'){{$message}}@enderror</span> <br>
                    <div id="items"></div>

                    <div class="row">
                        <div class="col-4">
                            <div class="form-group">
                    <label for="cost_wod">Cost without discount</label><br>
                    <input required type="text" id="cost_wod" name="cost_wod" class="cost_wod form-control" value="{{$invoice->total_cost}}" autocomplete="off"><br>
                    <span id="SpanCost" class="error">@error('cost_wod'){{$message}}@enderror</span> <br>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="form-group">
                                <label for="discount">Discount in %</label><br>
                                <input required type="text" id="discount" name="discount" class="discountcost form-control" size="50" value=0 ><br>
                                <span id="SpanDiscount" class="error">@error('discount'){{$message}}@enderror</span> <br>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="form-group">
                                <label for="tax">Tax %</label><br>
                                <input required type="text" id="tax" name="tax" class="tax form-control" size="50" value=18><br>
                                <span id="SpanTax" class="error">@error('tax'){{$message}}@enderror</span> <br>
                            </div>
                        </div>
                        </div>
                        <div class="row">
                            <div class="col-4">
                                <div class="form-group">
                    <label for="dcost">Price with discount and tax</label><br>
                    <input required type="text" id="dcost" name="dcost" class="dcost form-control" value="{{$invoice->final_cost}}" autocomplete="off"><br>
                    <span id="SpanDcost" class="error">@error('dcost'){{$message}}@enderror</span> <br>
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="form-group">
                    <label for="advance">Advance payment</label><br>
                    <input required type="text" id="advance" name="advance" class="advance form-control"
                           onkeyup="AdvanceValue()" value="{{$invoice->advance}}" autocomplete="off"><br>
                    <span id="SpanAdvance" class="error">@error('advance'){{$message}}@enderror</span> <br>
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="form-group">
                    <label for="due">Due amount</label><br>
                    <input required type="text" id="due" name="due" class="due form-control" value="{{$invoice->due}}" autocomplete="off"><br>
                    <span id="SpanDue" class="error">@error('due'){{$message}}@enderror</span> <br>
                                </div>
                            </div>
                        </div>


                    <button type="submit" class="btn btn-success" id="submit">Update</button>
                </div>

            </form>
                    </div>
                </div>
    </div>
    @else
        <div class="container">
            <div class="bg-white m-3 p-3">
        <form method="post" action="{{route('invoice.store')}}">
            @csrf
            <div id="invoice">
                <form id="AddForm" name="addForm" method="post">
                    @csrf
                    <div id="item-container">
                    </div>
                    <ul id="myUL"></ul>
                    <a class="text-white btn btn-primary" style="text-decoration: none" id="add-new-item">Add New Item</a>
                    <br/>
                    <hr/>

                </form><br>
                <span id="SpanForm" class="error">@error('addForm'){{$message}}@enderror</span> <br>
                <div id="items"></div>

                <div class="row">
                    <div class="col-4">
                        <div class="form-group">
                            <label for="cost_wod">Cost without discount</label>
                            <input required type="text" id="cost_wod" name="cost_wod" class="cost_wod form-control" value="{{@old('cost_wod')}}" readonly>
                            <span id="SpanCost" class="error">@error('cost_wod'){{$message}}@enderror</span>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="form-group">
                        <label for="discount">Discount in %</label>
                        <input required type="number" id="discount" name="discount" class="discountcost form-control" size="50" value=0
                               onkeyup="itemValue()">
                            <span id="SpanDiscount" class="error">@error('discount'){{$message}}@enderror</span>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="form-group">
                        <label for="tax">Tax %</label>
                        <input required type="number" id="tax" name="tax" class="tax form-control" size="50" value=18
                               onkeyup="itemValue()">
                        <span id="SpanTax" class="error">@error('tax'){{$message}}@enderror</span>
                    </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-4">
                        <div class="form-group">
                            <label for="dcost">Cost with discount and tax</label>
                            <input type="text" id="dcost" name="dcost" class="dcost form-control" readonly value="{{@old('dcost')}}">
                            <span id="SpanDcost" class="error">@error('dcost'){{$message}}@enderror</span>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="form-group">
                            <label for="advance">Advance payment</label>
                            <input required type="text" id="advance" name="advance" class="advance form-control"
                                   onkeyup="AdvanceValue()" value="0"><br>
                            <span id="SpanAdvance" class="error">@error('advance'){{$message}}@enderror</span>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="form-group">
                            <label for="due">Due amount</label>
                            <input required type="text" id="due" name="due" class="due form-control" value="{{@old('due')}}">
                            <span id="SpanDue" class="error">@error('due'){{$message}}@enderror</span>
                        </div>
                    </div>

                </div>

                <button type="submit" class="btn btn-success" id="submit">Submit</button>
            </div>

        </form>
        </div>
        </div>

    @endif

@endsection


@section('JsSection')
    <script src="{{ asset('js/InvoiceForm.js') }}"></script>
    <script src="{{asset('vendor/jquery/jquery-3.2.1.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/animsition/js/animsition.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/bootstrap/js/popper.js')}}"></script>
    <script src="{{asset('vendor/bootstrap/js/bootstrap.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/select2/select2.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/daterangepicker/moment.min.js')}}"></script>
    <script src="{{asset('vendor/daterangepicker/daterangepicker.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/countdowntime/countdowntime.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('js/main.js')}}"></script>

@endsection

src/OnlinePayment/newProject/resources/views/InvoiceItem/InvoiceItemView.blade.php
@extends('layouts.app')
@section('CssSection')

    <link rel="stylesheet" type="text/css" href="{{asset('css/company.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/bootstrap/css/bootstrap.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('fonts/font-awesome-4.7.0/css/font-awesome.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('fonts/Linearicons-Free-v1.0.0/icon-font.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/animate/animate.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/css-hamburgers/hamburgers.min.css"')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/animsition/css/animsition.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/select2/select2.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/daterangepicker/daterangepicker.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('css/util.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('css/main.css')}}">
@endsection
@if (session('status'))
    <div class="alert alert-success">{{session('status')}}</div>
@endif

@section('body')

    <div class="container bg-white p-4">
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <button class="btn btn-primary text-white"><a class="text-white" style="text-decoration: none" href="{{route('invoice.create')}}">Add New Invoice</a></button>
    <br/>
    <hr/>

    <div id="invoice_details">
        <table class="table table-hover" id="myTable">
            <thead>
            <tr>
                <th scope="col" class="page_sort" id="id">S No.</th>
                <th scope="col" class="page_sort" id="invoice">Invoice</th>
                <th scope="col">View</th>
                @canany(['update_invoice', 'delete_invoice'])
                    <th scope="col">Edit</th>
                    <th scope="col">Delete</th>
                @endcanany
            </tr>
            </thead>
            <tbody id="invoice_details_table">
            <?php $index=1;?>
            @foreach($invoice as $v)

                <tr>
                    <td >{{$index}}</td>
                    <td >Invoice {{$v->id}}/2022</td>
                    <td><a class="fa fa-eye" href="{{route('invoice.show', $v->id)}}"></a></td>
                    @canany(['update_invoice', 'delete_invoice'])
                        <td><a class="fa fa-edit" href="{{route('invoice.edit', $v->id)}}"></a></td>
                        <td>
                            <form action="{{route('invoice.destroy', $v->id)}}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="fa fa-trash"></button>
                            </form>
                        </td>
                    @endcanany
                </tr>
                <?php $index++;?>
            @endforeach
            </tbody>
        </table>
        <br/>
        <hr/>

    </div>
    </div>


@endsection


@section('JsSection')
    <script src="{{ asset('js/UserRetrieve.js') }}"></script>

    <script src="{{asset('vendor/jquery/jquery-3.2.1.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/animsition/js/animsition.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/bootstrap/js/popper.js')}}"></script>
    <script src="{{asset('vendor/bootstrap/js/bootstrap.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/select2/select2.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/daterangepicker/moment.min.js')}}"></script>
    <script src="{{asset('vendor/daterangepicker/daterangepicker.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/countdowntime/countdowntime.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('js/main.js')}}"></script>

@endsection

src/OnlinePayment/newProject/resources/views/InvoiceItem/Preview.blade.php
@extends('layouts.app')
@section('CssSection')

    <link rel="stylesheet" type="text/css" href="{{asset('css/company.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/bootstrap/css/bootstrap.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('fonts/font-awesome-4.7.0/css/font-awesome.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('fonts/Linearicons-Free-v1.0.0/icon-font.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/animate/animate.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/css-hamburgers/hamburgers.min.css"')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/animsition/css/animsition.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/select2/select2.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendor/daterangepicker/daterangepicker.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('css/util.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('css/main.css')}}">

    <link href="{{ asset('css/preview.css') }}" rel="stylesheet">

@endsection
@section('body')
    <div id="invoice">
        <div class="invoice overflow-auto">
            <div id="preview_table">
                <header>
                    <div class="row">

                        <div class="col company-details">
                            <h2 id="name" class="display-4">{{$invoice->company->company_name}}</h2>
                            <div id="address">{{$invoice->company->location}}</div>
                            <div id="contact">{{$invoice->company->phone}}</div>
                            <div id="email">{{$invoice->company->email}}</div>
                        </div>
                    </div>
                </header>
                <main>

                    <div class="row contacts">
                        <div class="col invoice-details">
                            <h1 id="invoice-id"></h1>
                            <div id="date">Date of Invoice: {{$invoice->updated_at->format('d-m-Y')}}</div>
                            <div id="duedate">Due Date: {{$invoice->updated_at->add(new DateInterval('P15D'))->format('d-m-Y')}}</div>
                        </div>

                    </div>
                    <table border="0" cellspacing="0" cellpadding="0">
                        <thead>
                        <tr>
                            <th class="text-left">SN</th>
                            <th class="text-center">Items</th>
                            <th class="text-center">Unit cost</th>
                            <th class="text-center">Quantity</th>
                            <th class="text-right">TOTAL</th>
                        </tr>
                        </thead>
                        <tbody id="preview">

                        <?php $index=1;?>
                        @foreach ($arr as $k=>$v)
                            @foreach ($v as $key=>$value)
                                <tr>
                                    <td class="text-left">{{$index}}</td>
                                    <td class="text-center">{{$value['name']}}</td>
                                    <td class="text-center">{{$value['cost']}}</td>
                                    <td class="text-center">{{$value['quantity']}}</td>
                                    <td class="text-right">{{$value['total']}}</td>
                                </tr>
                            @endforeach
                            <?php $index++;?>
                        @endforeach
                        </tbody>


                        <tfoot>
                        <tr>
                            <td colspan="2"></td>
                            <td colspan="2">SUBTOTAL</td>
                            <td id="total">{{$invoice->total_cost}}</td>
                        </tr>
                        <tr>
                            <td colspan="2">DISCOUNT</td>
                            <td colspan="2" id="discount">{{$invoice->discount}}%</td>
                            <td id="discounted_price">{{$discounted_cost}}</td>
                        </tr>
                        <tr>
                            <td colspan="2">TAX</td>
                            <td colspan="2" id="tax">{{$invoice->tax}}</td>
                            <td id="tax_price">{{$invoice->final_cost}}</td>
                        </tr>
                        <tr>
                            <td colspan="2"></td>
                            <td colspan="2">TOTAL</td>
                            <td id="grand_total"></td>
                        </tr>
                        </tfoot>
                    </table>
                    <div class="thanks">Thank you!</div>
                    <div class="notices">
                        <div>NOTICE:</div>
                        <div class="notice">A finance charge of 1.5% will be made on unpaid balances after 30 days.</div>
                    </div>
                </main>
                <footer>
                    Invoice was created on a computer and is valid without the signature and seal.
                </footer>
            </div>
            <div></div>
        </div>
    </div>
@endsection
@section('JsSection')
    <script src="{{ asset('js/UserRetrieve.js') }}"></script>

    <script src="{{asset('vendor/jquery/jquery-3.2.1.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/animsition/js/animsition.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/bootstrap/js/popper.js')}}"></script>
    <script src="{{asset('vendor/bootstrap/js/bootstrap.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/select2/select2.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/daterangepicker/moment.min.js')}}"></script>
    <script src="{{asset('vendor/daterangepicker/daterangepicker.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendor/countdowntime/countdowntime.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('js/main.js')}}"></script>

@endsection